components:
  application:
    Name: application_name
    Profile: dev
  gin:
    port: 8080
  redis:
    rds:
      - Name: root
        Cluster:
          Addrs:
            - 127.0.0.1:6379
            - 127.0.0.1:6380
            - 127.0.0.1:6381
            - 127.0.0.1:6382
            - 127.0.0.1:6383
            - 127.0.0.1:6384
          Password: test
          MaxRedirects: 0
          ReadOnly: false
          RouteByLatency: false

          # timeout
          DialTimeout: 10
          ReadTimeout: 10
          WriteTimeout: 10

          PoolSize: 15 # 连接池容量
          PoolTimeout: 5 # 连接池超时
          IdleTimeout: 5
          IdleCheckFrequency: 60 # 闲置检查
        Network: tcp
        Addr: 127.0.0.1:6379
        Password:
        DB: 0
        MaxRedirects: 0
        DialTimeout: 10
        ReadTimeout: 10
        WriteTimeout: 10
        PoolSize: 15 # 连接池容量
        PoolTimeout: 5 # 连接池超时
        IdleTimeout: 5
        IdleCheckFrequency: 60 # 闲置检查
        ReadOnly: false
  zap:
    addCallerSkip: 0
    requestId: true
    console:
      enable: true
      level: debug
      encoder:
        messageKey: msg
        levelKey: level
        timeKey: time
        nameKey: logger
        callerKey: file
        stacktraceKey: stacktrace
        lineEnding: \n
        timeFormat: 2006-01-02T15:04:05.000
    files:
      - enable: true
        level: debug
        encoder:
          messageKey: msg
          levelKey: level
          timeKey: time
          nameKey: logger
          callerKey: file
          stacktraceKey: stacktrace
          lineEnding: \n
          timeFormat: 2006-01-02T15:04:05.000
        logger:
          filename: gcomponent_zap.log
          maxsize: 128
          maxage: 7
          maxbackups: 30
          localtime:
          compress: false
  web:
    port: 8080
  gorm:
    dataSources:
      - name: test
        database: root
        username: root
        password: root
        url: localhost:3306
        MaxIdleConns: 100
        MaxOpenConns: 10
        ConnMaxLifetime: 60

  wechat-warning:
    url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=XXX
    enable: true
  optimize:
    pprof:
      port: 19190
      enable: true
